# Generated by Django 4.0.6 on 2022-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_question_answer_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('fac_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('notes', models.FileField(blank=True, upload_to='docs')),
                ('pre_question', models.FileField(blank=True, upload_to='docs')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Option1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Option2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Option3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Option4',
            new_name='option4',
        ),
    ]
