# Generated by Django 4.0.6 on 2022-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_academic_rename_option1_question_option1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='academic',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/academic/'),
        ),
    ]
